version: 2
jobs:

  qa:
    docker:
      - image: circleci/node:14
      - image: postgres
        environment:
          POSTGRES_PASSWORD: password
      - image: minio/minio
        environment:
          MINIO_ACCESS_KEY: accessKeyId
          MINIO_SECRET_KEY: secretAccessKey
        command: server /data
      - image: mongo
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Compile modules
          command: yarn compile
      - run:
          name: Run linters
          command: yarn lint
      - run:
          name: Run tests and calculate code coverage
          command: npm run coverage
      - run:
          name: Publish code coverage report
          command: yarn publish-coverage

  publish-website:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Compile website
          command: yarn compile --scope=@staticdeploy/website
      - run:
          name: Install staticdeploy cli
          command: |
            yarn global add @staticdeploy/cli
            echo 'export PATH=$PATH:$(yarn global bin)' >> $BASH_ENV
      - run:
          name: Create website bundle
          command: staticdeploy bundle --config website/staticdeploy.config.js
      - run:
          name: Deploy website bundle
          command: staticdeploy deploy --config website/staticdeploy.config.js

  docker-build-push:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install dependencies (commands below need lerna)
          command: yarn install --frozen-lockfile
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Set $DOCKER_TAG
          command: echo 'export DOCKER_TAG=${CIRCLE_TAG:-$CIRCLE_BRANCH}' >> $BASH_ENV
      - run:
          name: Build docker image
          command: yarn docker:build
      - run:
          name: When building a git tag, tag the image as latest
          command: |
            if [ ! -z $CIRCLE_TAG ]; then \
              yarn docker:tag-latest \
            ; fi
      - run:
          name: Push docker image
          command: yarn docker:push

  npm-publish:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies (commands below need lerna)
          command: yarn install --frozen-lockfile
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Compile modules
          command: yarn compile
      - run:
          name: Publish npm modules
          command: yarn lerna publish from-git --yes

workflows:
  version: 2
  qa-docker-npm:
    jobs:
      - qa:
          # Run for all branches and all tags
          filters:
            tags:
              only: /.*/
      - publish-website:
          requires:
            - qa
          # Run for all branches and all tags
          filters:
            tags:
              only: /.*/
      - docker-build-push:
          requires:
            - qa
          # Run for all branches and all tags
          filters:
            tags:
              only: /.*/
      - npm-publish:
          requires:
            - qa
          # Run only for tags starting with a v, don't run for branches
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
